name: dashboard

services:
  db:
    container_name: dashboard-db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dashboard_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - default

  backend:
    container_name: dashboard-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "poetry install --no-root && uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/workspace
      - ./.env:/workspace/.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_started
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/dashboard_db
      FRONTEND_ORIGINS: http://localhost:3000
      PYTHONPATH: /workspace
      # --- Variables de Seguridad Mapeadas desde .env ---
      AUTH_SECRET: ${AUTH_SECRET}
      ROOT_AUTH_HASH: ${ROOT_AUTH_HASH}
    networks:
      - default

  frontend:
    container_name: dashboard-frontend
    image: m4r4v/frontend:latest
    command: pnpm dev --host
    volumes:
      - ./frontend/app:/workspace/app
    working_dir: /workspace/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:8000
    networks:
      - default

  docs:
    container_name: dashboard-docs
    image: m4r4v/frontend:latest
    command: pnpm dev
    volumes:
      - ./docs:/workspace
    working_dir: /workspace
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
    networks:
      - default

networks:
  default:
    name: dashboard_default
