[tool.poetry]
name = "dashboard-backend"
version = "0.1.0"
description = "API oficial del Dashboard"
authors = ["m4r4v"]
readme = "README.md"
packages = [{include = "api"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.128.0"
uvicorn = {extras = ["standard"], version = "^0.40.0"}
# NUEVAS DEPENDENCIAS HITO 3
sqlmodel = "^0.0.16"
asyncpg = "^0.29.0"
alembic = "^1.13.1"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
argon2-cffi = "^25.1.0"
python-jose = {extras = ["cryptography"], version = "^3.5.0"}
# CORRECCIÓN HITO 6: Versión flexible para evitar bloqueo SemVer 0.x
python-multipart = "*"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.14"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I"]